apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: ps61qhmql-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-126fa8b685.b32y.p3.openshiftapps.com/rhtap/rhtap-qe:cbc77f63740617fe0e81a7276b90a4973e99f21d@sha256:54e104795c82079c467ad55540c22efc001090cd686c36e6118faf1ba4ce77c5
          name: container-image
